### ISSUE TITLE
Multiply sertificates

### ISSUE THREAD

**Issue by pilot87** [nginx/unit#484] opened 2020-10-22 04:49 UTC
I have two domine names with two different certificates for my site (one IP adress), how could I manage to use bouth of them? Becouse listners in config.json do not support URL names, but only IP

**Comment by VBart** [comment] 2020-10-22 04:56
Multiple certificates on the same IP can only work with TLS extension called SNI. While this features is planned, currently Unit doesn't support SNI extension.

**Comment by VBart** [comment] 2021-02-04 23:49
Duplicate of #406.

**Closed by VBart** 2021-02-04 23:49 UTC
Labels: enhancement
