### ISSUE TITLE
Installing UNIT - go1.9 errors

### ISSUE THREAD

**Issue by Tricky-Ricky** [nginx/unit#281] opened 2019-07-18 04:05 UTC
Installed Unit and got the following error:
Errors were encountered while processing:
 /tmp/apt-dpkg-install-foRb5m/48-unit-go1.9_1.9.0-1~bionic_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

Otherwise installation complete

**Comment by Tricky-Ricky** [comment] 2019-07-20 13:40
After having issues with WP and Unit, I uninstalled Nginx and Unit again, Using purge and then deleting any corresponding directories and files left over - I rebooted my server and re-installed nginx and unit again. Again I got another error with this:

> Unpacking unit-ruby (1.9.0-1~bionic) ...
> Errors were encountered while processing:
>  /tmp/apt-dpkg-install-hEW2SF/45-unit-go1.9_1.9.0-1~bionic_amd64.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)

Unit continued to install and is running, Not sure what these errors are about

**Comment by Tricky-Ricky** [comment] 2019-07-22 05:32
@defanator @thresheek 
Over the weekend I uninstalled nginx and unit - Came across this a couple of times...

It seems that nginx and unit was still running in the background somehow after:
`sudo apt remove --purge`
Some files and directories were still left - I had to manually go through and delete each folder, and also remove the daemon process to start after reboot.

Once the directories and daemon were removed - Only then did Unit and Nginx install again without any errors.

So possible bug in the uninstall?

**Comment by thresheek** [comment] 2021-12-22 11:16
We're routinely checking install, uninstall, and upgrades on all supported distros but we've never seen that happening.

If that is still relevant and latest packages exhibit the issue you're seeing:
- what OS is that?
- is it virtualized / bare-metal / containerized?
- anything that might make your setup different from a typical cloud environemtn or bare metal server? e.g. lack of specific directories or something similar?
- which directories are left over when you're purging unit and its modules?

So in sum, I would need a way to reproduce this behaviour.

**Comment by thresheek** [comment] 2022-10-27 11:25
Closing due to a feedback timeout.

**Closed by thresheek** 2022-10-27 11:25 UTC
