### ISSUE TITLE
Infinite redirect on static share resources

### ISSUE THREAD

**Issue by ryan-marshall-evident** [nginx/unit#975] opened 2023-10-18 12:40 UTC
I have been trying to set up a PHP application that also serves static files. Unfortunately, when I request the static assets, I get a 301 redirect to the same file with a `/` appended.

So `http://localhost/file.html` redirects to `http://localhost/file.html/` which redirects to `http://localhost/file.html//`.

I have tried to strip back the configuration to just serve the static files (see config below), however, this still results in the redirects.

```json
{
    "listeners": {
        "*:80": {
            "pass": "routes"
        }
     },

    "routes": [
        {
            "action": {
                "share": "/www/public$uri"
            }
        }
    ],
    "settings": {
        "http": {
            "log_route": true
        }
    }
}
```
![image](https://github.com/nginx/unit/assets/134501791/637c3f2a-121d-4e8d-8609-b4e58edc2cf8)

![image](https://github.com/nginx/unit/assets/134501791/19c84dd6-6bea-4474-8637-63ed0fee7556)

**Comment by lcrilly** [comment] 2023-10-18 14:57
I cannot reproduce. This looks like a Docker container (judging by the hostname). Could you share a Dockerfile that exhibits this behaviour?

**Comment by ryan-marshall-evident** [comment] 2023-10-19 06:04
Here's a stripped-down docker file I've tested this on:

```
FROM unit:1.31.0-php8.2@sha256:3489384ba2bdfa707d08431b335b0f776c206863e93e5998892199036d767468 as dev

COPY <<EOF /docker-entrypoint.d/config.json
{
    "listeners": {
        "*:80": {
            "pass": "routes"
        }
     },

    "routes": [
        {
            "action": {
                "share": "/www/public$uri"
            }
        }
    ],
    "settings": {
        "http": {
            "log_route": true
        }
    }
}
EOF

COPY <<EOF /www/public/file.html
<html>
	<head>
		<title>Unit</title>
	</head>
	<body>
		<h1>Unit</h1>
		<p>Hello world!</p>
	</body>
</html>
EOF

WORKDIR /www

EXPOSE 80
```

Running on docker desktop version 4.24.0 (122432).

**Comment by tippexs** [comment] 2023-10-19 06:44
I see, According to the documentation and DIFFERENT from what you have shared earlier, this configuration misses the `$uri` at the end of the share configuration. With this UNIT will not know anything about the file you want to serve from disk.

**Comment by tippexs** [comment] 2023-10-19 07:26
I had another look on this. The configuration you are creating in you `Dockerfile` will not arrive in your container as you think. `$uri` WILL NOT BE interpreted as a string as it includes a `$` and therfore it should be variable name.

Simple Test:
```Dockerfile
COPY <<EOF /tets.txt

abc $123

EOF
```

```bash
$ docker run --rm -it -P tippexs/unit:fi cat /tets.txt

abc
```

We have to escape the `$` to make this work:
```Dockerfile
COPY <<EOF /docker-entrypoint.d/config.json
{
    "listeners": {
        "*:80": {
            "pass": "routes"
        }
     },

    "routes": [
        {
            "action": {
                "share": "/www/public\$uri"
            }
        }
    ],
    "settings": {
        "http": {
            "log_route": true
        }
    }
}
EOF
```

Going to close this issue now.

**Closed** 2023-10-19 07:26 UTC

**Comment by ryan-marshall-evident** [comment] 2023-10-19 09:26
@tippexs, thanks for your response. I've just tested this and it worked a treat. I had a feeling it was going to be something straightforward.
