### ISSUE TITLE
nginx-unit centos 7.5 pid startup error.

### ISSUE THREAD

**Issue by devinacosta** [nginx/unit#128] opened 2018-06-04 07:07 UTC
I am running the latest CentOS 7.5, and installed Unit from the CentOS Repos. I have installed the following packages:

unit-1.1-1.el7.ngx.x86_64
unit-php-1.1-1.el7.ngx.x86_64

However when I start the unit process it fails with:

# systemctl start unit
Job for unit.service failed because a timeout was exceeded. See "systemctl status unit.service" and "journalctl -xe" for details.

# journalctl -xe
Jun 04 03:04:40 unit.linuxstack.cloud unitd[2044]: 2018/06/04 03:04:40 [info] 2044#2044 unit started
Jun 04 03:04:40 unit.linuxstack.cloud systemd[1]: PID file /run/unit.pid not readable (yet?) after start.

[root@unit log]# cat unitd.log
2018/06/04 03:04:40 [info] 2046#2046 discovery started
2018/06/04 03:04:40 [notice] 2046#2046 module: php 5.4.16 "/usr/lib64/unit/modules/php.unit.so"
2018/06/04 03:04:40 [info] 2047#2047 controller started
2018/06/04 03:04:40 [notice] 2045#2045 process 2046 exited with code 0
2018/06/04 03:04:40 [info] 2048#2048 router started
2018/06/04 03:06:10 [notice] 2045#2045 process 2047 exited with code 0
2018/06/04 03:06:10 [notice] 2045#2045 process 2048 exited with code 0

any ideas?

**Comment by devinacosta** [comment] 2018-06-04 07:11
If i delete the PID options in /etc/sysconfig/unit, i can get it to startup without issues?

**Comment by defanator** [comment] 2018-06-04 07:22
Duplicate of #120, already fixed in master, fix will be included into next release packages.

**Closed by defanator** 2018-06-04 07:22 UTC
