### ISSUE TITLE
Possible not initialized use

### ISSUE THREAD

**Issue by geyslan** [nginx/unit#455] opened 2020-08-14 12:06 UTC
https://github.com/nginx/unit/blob/6473d4b65a99aa10d509220fb99d8c4f65631ed0/src/nxt_conn_write.c#L269

In a not described OS `res` could be returned not initialized.

https://github.com/nginx/unit/blob/6473d4b65a99aa10d509220fb99d8c4f65631ed0/src/nxt_lib.c#L98

In a not described OS `n` could be used with no valid value.

**Comment by mar0x** [comment] 2020-08-14 14:01
Both issues caused by unsupported platform.

PR #452 is an attempt to resolve first issue. 
Second issue can be easily resolved by n = 1 default. @geyslan , what platform you are using?

**Comment by geyslan** [comment] 2020-08-14 15:20
@mar0x I'm using Linux x64. The issues were caught by _cppcheck_.

PR #452 only add a new platform. I would consider to initialize `res` to -1 in the declaration.

`ssize_t  res = -1;`

**Closed** 2020-10-14 15:43 UTC
