### ISSUE TITLE
HTTP request is sent twice in Node app

### ISSUE THREAD

**Issue by b1nks** [nginx/unit#1416] opened 2024-09-06 21:58 UTC
I'm using unit:node Docker image and I encountered double sending of http requests. 

Looks like a bug, but I'm not qualified enough to dive deeper into the problem.

The situation can be repeated on the simplest configuration:

- Use a pure image unit:node, basic Unit configuration and copy there a .js file with sending an http request from anywhere
```
const http = require("unit-http");

const options = {
  hostname: "<your hostname>",
  port: 80,
  path: "/<your path>",
  method: "GET",
};

const req = http.request(options, (res) => {
  let responseData = "";

  res.on("data", (chunk) => {
    responseData += chunk;
  });

  res.on("end", () => {
    console.log("Response:", responseData);
  });
});

req.on("error", (error) => {
  console.error("Error:", error);
});

req.end();

const server = http.createServer();

server.listen();
```

- When we launch the container we will see one line in the logs, but when we look at the logs of the target server we will actually see two requests

**Comment by hongzhidao** [comment] 2024-09-09 10:55
Hi @b1nks,
> When we launch the container we will see one line in the logs, but when we look at the logs of the target server we will actually see two requests

What do the two request logs in the target server look like?

**Comment by b1nks** [comment] 2024-09-09 13:47
I initially encountered this problem when sending a message via the Telegram API. I received two messages instead of one sent. 

But this situation is easily repeated, for example, by sending a request to webhook.site. The screenshots show that the code I provided above recorded the success message once, but on the site we see two incoming requests.

<img width="848" alt="Screenshot 2024-09-09 at 16 44 21" src="https://github.com/user-attachments/assets/3b3eb8af-2e09-4778-bf0a-8a9fa5bc284b">
<img width="1091" alt="Screenshot 2024-09-09 at 16 44 45" src="https://github.com/user-attachments/assets/bef33c25-ad83-4bc3-b9b7-9f6e754d7eb0">

**Comment by hongzhidao** [comment] 2024-09-09 14:35
I tried your code to send to the local server running nginx.
Here's my configuration.
```
{
   "listeners": {
      "*:8080": {
          "pass": "applications/node"
      }
  },
  "applications": {
      "node": {
          "type": "external",
          "executable": "/usr/bin/node",
          "arguments": ["/tmp/app.js"]
      }
  }
}
```
But I only see one access log in nginx. Could you try it with a local server like nginx?
Btw, I didn't use Docker.

**Comment by b1nks** [comment] 2024-09-09 20:38
I started another container with `nginx:latest` and sent a request to it. The result is exactly the same. 

<img width="696" alt="Screenshot 2024-09-09 at 23 15 02" src="https://github.com/user-attachments/assets/f4cdccb0-1b87-46c8-b02c-c0956a21f2ca">
<img width="592" alt="Screenshot 2024-09-09 at 23 15 49" src="https://github.com/user-attachments/assets/99665a08-5558-4e3e-a03c-d3fad1a272f8">

Later I will try to do the same test without using Docker, however, we cannot ignore the fact that the Docker image does not work correctly, because this behavior occurs even with the most basic configuration

**Comment by b1nks** [comment] 2024-09-14 01:28
I ran this config without Docker and everything is fine, no double request sending occurs

**Comment by b1nks** [comment] 2024-09-23 22:35
Hello. Is there any news on this issue?

**Comment by javorszky** [comment] 2024-09-25 14:06
> Hello. Is there any news on this issue?

Hi! Apologies, we've been busy releasing version 1.33 and some associated tasks. I am going to look at this this week and should have an update for you soon.

**Comment by javorszky** [comment] 2024-10-01 13:21
Additional details for others to replicate this that was needed to look into this:

1. go to https://webhook.site. That will give you a unique URL that you can use to plug into the `options` object in the example code. Mine looks like this:
  ```js
  const options = {
    hostname: "webhook.site",
    port: 80,
    path: "/21d0ae48-4210-4c87-b4a5-a81649357386",
    method: "GET",
  };
  ```
2. in the code the `http.createServer()` call does not take an option and handler function. It defaults to an empty object for the options (which is fine as we're not propagating the options to node's http constructor), but more importantly the request handler function is undefined, which means even though the node app runs and the server listens, when an incoming request is received there's nothing to do anything with it, which means the request will time out. A fix for that is
  ```js
  const server = http.createServer({}, (req, res) => {
    res.writeHead(200, {"Content-Type": "text/plain"});
    res.end("Hello, Node.js on Unit!")
  });
  ```
  That way when we send a request to Unit, we get a response.
3. The way the example code is written will make the app immediately send a request to the hot+path that's in the options object _once_ per boot up, but subsequent requests to Unit, and therefore the app, will mean there will be no additional requests sent to webhook.site.

@b1nks do you have a more functional code you can paste here where you can reproduce the issue that when you send 1 request to Unit, it results in 2 requests to webhook.site?

**Comment by b1nks** [comment] 2024-10-01 17:49
I initially got this problem when I added a handler for a Mongo data change event to my app. 
I experimented with the code and configuration and found that the error could be reproduced with the most basic configuration, which I provided in the first message. 

My app is a fairly simple configuration with express.js and of course I use a more complete initialization from the documentation. 
I have several handler functions and when they work I do not observe double sending of the request. 
Below is a more accurate example of my configuration

_Dockerfile_
```
FROM unit:node

COPY src/ /www/
COPY unit-config.json /docker-entrypoint.d/

RUN cd /www/ && npm install && npm link unit-http
```

_unit-config.json_
```
{
  "listeners": {
    "*:8080": {
      "pass": "routes"
    }
  },

  "routes": [
    {
      "action": {
        "pass": "applications/express"
      }
    }
  ],

  "applications": {
    "express": {
      "type": "external",
      "working_directory": "/www/",
      "executable": "/usr/bin/env",

      "arguments": [
        "node",
        "--loader",
        "unit-http/loader.mjs",
        "--require",
        "unit-http/loader",
        "index.js"
      ]
    }
  }
}

```

_index.js_
```
import http from "http";
import mongoose from "mongoose";
import express from "express";
import { User, Group } from "./models.js";
import { handlers } from "./handlers.js";

await mongoose.connect(...)

// Here is the problem
User.watch(
  [
    {
      $match: {
        operationType: "update",
        "updateDescription.updatedFields.active": { $exists: true },
      },
    },
  ],
  { fullDocument: "updateLookup" }
).on("change", async (data) => {
  console.log(data);

  await handlers.handleChangeActive(data.fullDocument);
});

const app = express();

app.get(...);

const server = http.createServer(app);

server.listen(PORT, HOST, () => {...});
```

_handleChangeActive_ can have any implementation, including sending a request to webhook.site. This is always a double send.

**Comment by javorszky** [comment] 2024-10-02 08:52
Thank you for this. To make sure I understand your flow correctly:

1. given the above code you send 1 (one) request to the Unit application
2. that request results in the User model being updated
3. that update kicks off a call to `handleChangeActive`
4. that is always a double send

As I don't have the actual application (I'm missing the models and handlers.js as well as the package.json) and I don't know enough about nodejs and mongoose here to fill in the blanks, and even then it would be different, could you double check something for me?

I'm curious, how many times is `User.watch.on("change")` getting called?

The question I'm trying to find out is whether the double call happens because the model has a double update, but each update correctly sends a single call to `handleActiveChange`, or it's an issue in Unit itself.

If you run this application on your host machine outside of Unit, does the issue get resolved?

**Comment by b1nks** [comment] 2024-10-02 11:30
Thanks for this clarifying question, it helped me to discover some facts that I hadn't noticed before. 
Apparently `User.watch.on("change")` is indeed called twice, although only one entry is always written to the container logs. 
I discovered this by adding a call to write to the database in `handleChangeActive`, which was not there before. 
The write happens twice.

However, I don't think that mongoose itself can be involved in this behavior, because I tried sending the request in other ways without the participation of any third-party libraries, including using a simple implementation of event emitter. 
And I always got the same effect.

Unfortunately, I can't run my application on the host machine, but I will try to make a similar configuration and make sure that it works correctly.

**Comment by javorszky** [comment] 2024-10-02 14:23
Can you link me to the event emitter example, or paste in a fully working code that I can copy paste as-is? It would help a lot if you had a minimum reproduction example we can look at so we can remove as much of the possibility of a user application doing unexpected things and hone in on Unit sending a double request.

**Comment by b1nks** [comment] 2024-10-09 20:06
Sorry for the long absence.

_Dockerfile_
```
FROM unit:node

COPY index.js /www/
COPY unit-config.json /docker-entrypoint.d/

RUN cd /www/ && npm link unit-http
```

_index.js_
```
const http = require("http");
const EventEmitter = require("events");

const myEmitter = new EventEmitter();

myEmitter.on("event", () => {
  const options = {
    hostname: "webhook.site",
    port: 80,
    path: "/dec14dea-3b30-4276-9e36-9974b8cf7fe5",
    method: "GET",
  };

  const req = http.request(options, (res) => {
    console.log(res.statusCode);
  });

  req.end();
});

myEmitter.emit("event");

http.createServer((req, res) => {
  res.writeHead(200, { "Content-Type": "text/plain" });
  res.end("Hello, Node.js on Unit!");
});


```

__unit-config.json__
```
{
  "listeners": {
    "*:8080": {
      "pass": "applications/node"
    }
  },

  "applications": {
    "node": {
      "type": "external",
      "working_directory": "/www/",
      "executable": "/usr/bin/env",

      "arguments": [
        "node",
        "--loader",
        "unit-http/loader.mjs",
        "--require",
        "unit-http/loader",
        "index.js"
      ]
    }
  }
}
```

**Comment by b1nks** [comment] 2024-10-14 01:00
oh.. 
Thank you for researching my question and thank you for the detailed answer!
That's probably what really confused me.

**Comment by javorszky** [comment] 2024-10-14 07:56
Hello!

That's all right, glad I could clarify things 🙂 . I'm going to close this issue as answered. Have an excellent week ahead!

**Closed by javorszky** 2024-10-14 07:56 UTC
