### ISSUE TITLE
Ruby Apps Using Bundler Fail Due to nxt_ruby Loading Rack

### ISSUE THREAD

**Issue by sshaw** [nginx/unit#91] opened 2018-04-02 03:55 UTC
Often times one will have version X of Rack installed but their application depends on version Y. This dependency on Y is usually handled via [Bundler](http://bundler.io/). 

Give a `config.ru` file for an application that uses Bundler, one would execute:

```
bundle exec rackup config.ru
```

To load version Y only instead of: 

```
rackup config.ru
```

Which may load version X before the Bundler code in the application can load version Y. When Bundler does attempt to load version Y, the following fatal error is given: 

```
2018/04/01 22:03:04 [alert] 4648#18991245 Ruby: /Users/sshaw/.rvm/gems/ruby-2.3.5/gems/bundler-1.15.4/lib/bundler/runtime.rb:317:in `check_for_activated_spec!': You have already activated rack 2.0.3, but your Gemfile requires rack 1.6.4. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
```

This is a problem with Unit because it [requires Rack](https://github.com/nginx/unit/blob/856826f535b662085fc563a02df2388d287ff374/src/ruby/nxt_ruby.c#L205) in order to create the application's entry point. As seen above, this version of Rack is not supported by the application it's trying to run.

**Comment by sshaw** [comment] 2018-04-02 04:06
May just want to check for a `Gemfile` in the application's home directory and do the bundler stuff prior to parsing `config.ru`. This should not affect the Bundler calls made by the application. 

I can put together a PR with this if you like.

**Comment by lexborisov** [comment] 2018-04-05 13:29
Hi @sshaw ,
I'm doing this task. You can send your PR and we will find the right solution.

Thanks!

**Comment by sshaw** [comment] 2018-04-06 04:28
@lexborisov checkout #93

**Comment by jfqd** [comment] 2020-07-06 07:35
Is there a solution for this issue? Every rack app has Gemfile, so is using bundler.

**Comment by VBart** [comment] 2020-07-06 09:11
@jfqd This ticket is a bit obsolete, since Unit uses bundler now. Could you elaborate more what's the issue is?

**Comment by jfqd** [comment] 2020-07-06 15:29
@VBart Thx for asking.

I am using rvm (Ruby Version Manager) and tried to push a config for a rails app (with Gemfile) on macOS (with homebrew):

```
curl -X PUT --unix-socket /usr/local/var/run/unit/control.sock http://localhost/config -d '{
    "listeners": {
        "*:3000": {
            "pass": "applications/myapp"
        }
    },
    "myapp": {
        "myapp": {
            "type": "ruby",
            "working_directory": "/Users/me/myapp",
            "script": "config.ru",
            "environment": {
                "RAILS_ENV": "stage",
                "GEM_HOME": "/Users/me/.rvm/gems/ruby-2.5.7@myapp",
                "GEM_PATH": "/Users/me/.rvm/gems/ruby-2.5.7@myapp:/Users/me/.rvm/gems/ruby-2.5.7@global",
                "PATH": "/Users/me/.rvm/gems/ruby-2.5.7@myapp/bin:/Users/me/.rvm/gems/ruby-2.5.7@global/bin:/Users/me/.rvm/rubies/ruby-2.5.7/bin:/Users/me/.rvm/bin:/usr/local/opt/curl/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
            }
        }
    }
}'
{
	"error": "Failed to apply new configuration."
}
```

The log:

```
2020/07/06 10:03:10 [info] 90791#12861426 "myapp" application started
2020/07/06 10:03:10 [alert] 90791#12861426 Ruby: Failed to require 'bundler/setup' package
2020/07/06 10:03:10 [alert] 90791#12861426 Ruby: /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/bundler/spec_set.rb:86:in `block in materialize': Could not find RedCloth-4.3.2 in any of the sources (Bundler::GemNotFound)
2020/07/06 10:03:10 [alert] 90791#12861426 from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/bundler/spec_set.rb:80:in `map!'
2020/07/06 10:03:10 [alert] 90791#12861426 from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/bundler/spec_set.rb:80:in `materialize'
2020/07/06 10:03:10 [alert] 90791#12861426 from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/bundler/definition.rb:170:in `specs'
2020/07/06 10:03:10 [alert] 90791#12861426 from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/bundler/definition.rb:237:in `specs_for'
2020/07/06 10:03:10 [alert] 90791#12861426 from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/bundler/definition.rb:226:in `requested_specs'
2020/07/06 10:03:10 [alert] 90791#12861426 from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/bundler/runtime.rb:101:in `block in definition_method'
2020/07/06 10:03:10 [alert] 90791#12861426 from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/bundler/runtime.rb:20:in `setup'
2020/07/06 10:03:10 [alert] 90791#12861426 from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/bundler.rb:149:in `setup'
2020/07/06 10:03:10 [alert] 90791#12861426 from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/bundler/setup.rb:20:in `block in <top (required)>'
2020/07/06 10:03:10 [alert] 90791#12861426 from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
2020/07/06 10:03:10 [alert] 90791#12861426 from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
2020/07/06 10:03:10 [alert] 90791#12861426 from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/bundler/setup.rb:20:in `<top (required)>'
2020/07/06 10:03:10 [alert] 90791#12861426 from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
2020/07/06 10:03:10 [alert] 90791#12861426 from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
2020/07/06 10:03:10 [alert] 90791#12861426 from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
2020/07/06 10:03:10 [notice] 89399#12741327 process 90791 exited with code 1
2020/07/06 10:03:10 [warn] 89402#12741331 failed to start application "myapp"
2020/07/06 10:03:10 [alert] 89402#12741331 failed to apply new conf
```

**Comment by mar0x** [comment] 2020-07-06 20:36
@jfqd Homebrew `unit-ruby` built against latest ruby in Brew (2.7.1_2) and alerts from the log confirmed this. Maybe this is the root of your issue?

If you want to use ruby from macOS distribution, please try attached [unit-ruby-macos.rb.zip](https://github.com/nginx/unit/files/4881090/unit-ruby-macos.rb.zip) formula: download it, unzip to `/usr/local/Homebrew/Library/Taps/nginx/homebrew-unit/Formula/unit-ruby-macos.rb` and install with `$ brew install unit-ruby-macos`.

Before you try to apply your Unit config, make sure `unit-ruby` was uninstalled or update application type with desired version: `"type": "ruby 2.5.7",` otherwise Unit will try to use highest version and you'll stay where you are.

**Comment by tippexs** [comment] 2022-11-17 11:27
Closing this issue due to our 90 days time-out.

**Closed by tippexs** 2022-11-17 11:27 UTC
