### ISSUE TITLE
Apparent Memory Leak in Router + Application

### ISSUE THREAD

**Issue by ehlertjd** [nginx/unit#168] opened 2018-09-21 14:59 UTC
Discovered in 1.3, reproducible in 1.4, using a python 2.7 application.

Attached zipfile with source and configuration which will reproduce the problem.
Changing the method of writing the file does not appear to make a difference.

Requires Docker and a tool that can send concurrent requests (e.g. [apache benchmark](http://httpd.apache.org/docs/2.4/programs/ab.html)) 
Steps:
-  execute run.sh, which will build and launch the unit application and a top window.
- Run multiple concurrent requests, and watch the top window. e.g.
  - `ab -c 32 -n 100 http://localhost:8080`
- You can stop the container by pressing `q` in the `top` window.

Memory usage for the application and router processes creep up, even across multiple runs, and never drop.

[unit-memleak.zip](https://github.com/nginx/unit/files/2405842/unit-memleak.zip)

**Comment by andrey-zelenkov** [comment] 2018-10-02 23:32
I can confirm increasing of memory usage. Starting from certain value memory usage significantly slow down, but still increases over the time.

@mar0x  agreed to take a look at this issue.

**Comment by mar0x** [comment] 2019-03-28 14:32
After investigation I've found this not a memory leak, but memory use caused by difference in communication speed between "application to router" and "router to client". Application send data to router using shared memory whereas router transfer response to client using TCP and it is much slower (even for localhost). Responses from the application "gets stuck" in router consuming shared memory which is shared between application and router.
Decreasing 'app->max_pending_responses' to 1 may help to limit memory consumption, but it requires to re-compile Unit and we steel need to think about shared memory limiting/releasing anyway, so I keep the issue open for now.

**Comment by mar0x** [comment] 2020-02-05 15:00
The issue is fixed in current master version. Major commit related to the issue is df7caf465072e171f88358b9e69c65b76d8efd25 and 8eba2e5c3d8537521d3e010025e6078bc1fd28d6 fixes issues, introduced earlier.

**Closed by mar0x** 2020-02-05 15:00 UTC
