### ISSUE TITLE
using unit for starlette/python application over ipv6 results in crash

### ISSUE THREAD

**Issue by sandeep-gh** [nginx/unit#874] opened 2023-05-12 07:28 UTC
My configuration is  as follows: 
```
 {
            "listeners": {
                 "[2001:19f0:1000:25ca:5400:4ff:fe6d:2abc]:1160": {
                    "pass": "routes"
                }
            },

            "routes": [
                {
                    "action": {
                        "pass": "applications/starlette"
                    }
                }
            ],

            "applications": {
                "starlette": {
                    "type": "python 3.11",
                    "path": "/var/www/run_unit_0/htdocs/webworks.monallabs.in/",
                    "home": "/var/www/run_unit_0/venv/",
                    "module": "webworks_monallabs",
                    "callable": "app"
                }
            }
        }

```
The error log shows:
```
ValueError: invalid literal for int() with base 10: '19f0:c:100::2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/run_unit_0/Builds/Python-3.11/lib/python3.11/asyncio/base_events.py", line 765, in call_soon
    handle = self._call_soon(callback, args, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/run_unit_0/Builds/Python-3.11/lib/python3.11/asyncio/base_events.py", line 781, in _call_soon
    handle = events.Handle(callback, args, self, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: <class 'asyncio.events.Handle'> returned a result with an exception set
2023/05/12 07:26:23.509 [debug] 98571#277060 [unit] recvmsg(10) failed: Resource temporarily unavailable (35)
2023/05/12 07:26:23.509 [debug] 98571#277060 [unit] port{98571,0} recvmsg -1
2023/05/12 07:26:23.509 [debug] 98571#277060 [unit] asgi_port_read(0xb26ab5b6108,0xb26a3291180): 2

```
The debug log:

` [unit] sendmsg(13, 16, 0): 16
2023/05/12 07:16:40.245 [debug] 45486#154438 [unit] port{97512,1} send 16 read_queue
2023/05/12 07:16:40.245 [debug] 45486#154438 [unit] asgi_port_read(0x9cd7cc02108,0x9cd1b8dfd80): 0
2023/05/12 07:16:40.245 [alert] 45486#154438 [unit] Python failed to call 'loop.call_soon'
ValueError: invalid literal for int() with base 10: '19f0:c:100::2'

2023/05/12 07:16:40.245 [debug] 97512#593595 *4 writev(27, 2): 193
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 event conn: 193 sent:193
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 timer disable: 0
2023/05/12 07:16:40.245 [debug] 97512#593595 work queue: fast
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 h1p conn sent
2023/05/12 07:16:40.245 [debug] 97512#593595 work queue: fast
2023/05/12 07:16:40.245 [debug] 97512#593595 mp 9CCCFF31900 release: 3
2023/05/12 07:16:40.245 [debug] 97512#593595 mp 9CCCFF31900 release: 2
2023/05/12 07:16:40.245 [debug] 97512#593595 work queue: fast
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 router http request done (rpc_data 0)
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 http request close handler
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 h1p request close
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 conf joint 9CCCFF36600 count: 2
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 h1p keepalive
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 setsockopt(27, 6, TCP_NODELAY): 1
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 h1p complete buffers
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 buf completion: 9CCCFF32000 9CCCFF32048
2023/05/12 07:16:40.245 [debug] 97512#593595 mp 9CCCFF31900 release: 1
2023/05/12 07:16:40.245 [debug] 97512#593595 work queue: read
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 kqueue conn read fd:27
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 conn read fd:27 rdy:0 cl:0 er:0 bl:0
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 timer add: 407564996±50 180000:407565000
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 timer previous: 407565000±50
2023/05/12 07:16:40.245 [debug] 97512#593595 timers changes: 1
2023/05/12 07:16:40.245 [debug] 97512#593595 timer rbtree insert: 407385000±50
2023/05/12 07:16:40.245 [debug] 97512#593595 timer found minimum: 407385000±50:407385000
2023/05/12 07:16:40.245 [debug] 97512#593595 kevent(21) changes:0 timeout:0
2023/05/12 07:16:40.245 [debug] 97512#593595 kevent(21): 1
2023/05/12 07:16:40.245 [debug] 97512#593595 kevent: id:27 ft:-1 fl:8025 ff:0 d:0 ud:9CCCFF25C00
2023/05/12 07:16:40.245 [debug] 97512#593595 timer expire minimum: 407384950:407385001
2023/05/12 07:16:40.245 [debug] 97512#593595 timer expire delete: 407385000±50
2023/05/12 07:16:40.245 [debug] 97512#593595 work queue: fast
2023/05/12 07:16:40.245 [debug] 97512#593595 http request pool release
2023/05/12 07:16:40.245 [debug] 97512#593595 mp 9CCCFF31900 release: 0
2023/05/12 07:16:40.245 [debug] 97512#593595 free(9CCCFF2DE00)
2023/05/12 07:16:40.245 [debug] 97512#593595 free(9CCCFF2F000)
2023/05/12 07:16:40.245 [debug] 97512#593595 free(9CCCFF36800)
2023/05/12 07:16:40.245 [debug] 97512#593595 free(9CCCFF31900)
2023/05/12 07:16:40.245 [debug] 97512#593595 work queue: read
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 kqueue conn read fd:27
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 kevent fd:27 eof
2023/05/12 07:16:40.245 [debug] 97512#593595 work queue: fast
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 h1p conn close
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 h1p shutdown
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 h1p complete buffers
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 h1p closing
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 h1p conn closing
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 conn close fd:27, to:0
2023/05/12 07:16:40.245 [debug] 97512#593595 work queue: close
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 conn close handler fd:27
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 timer delete: 407564996±50
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 timer change: 0±50:2
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 timer delete: 0±50
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/run_unit_0/Builds/Python-3.11/lib/python3.11/asyncio/base_events.py", line 765, in call_soon
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 socket close(27)
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 timer add: 0±50 0:407385001
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 timer change: 407385001±50:1
2023/05/12 07:16:40.245 [debug] 97512#593595 timers changes: 2
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 timer rbtree delete: 407564996±50
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 timer rbtree insert: 407385001±50
2023/05/12 07:16:40.245 [debug] 97512#593595 *4 timer found minimum: 407385001±50:407385001
2023/05/12 07:16:40.245 [debug] 97512#593595 kevent(21) changes:0 timeout:0
2023/05/12 07:16:40.246 [debug] 97512#593595 kevent(21): 0
2023/05/12 07:16:40.246 [debug] 97512#593595 timer expire minimum: 407384951:407385002
2023/05/12 07:16:40.246 [debug] 97512#593595 *4 timer expire delete: 407385001±50
2023/05/12 07:16:40.246 [debug] 97512#593595 work queue: fast
2023/05/12 07:16:40.246 [debug] 97512#593595 *4 conn close timer handler fd:-1
2023/05/12 07:16:40.246 [debug] 97512#593595 work queue: fast
2023/05/12 07:16:40.246 [debug] 97512#593595 *4 h1p conn free
2023/05/12 07:16:40.246 [debug] 97512#593595 mp 9CCCFF31D00 release: 0
2023/05/12 07:16:40.246 [debug] 97512#593595 free(9CCCFF2C700)
2023/05/12 07:16:40.246 [debug] 97512#593595 free(9CCCFF22400)
2023/05/12 07:16:40.246 [debug] 97512#593595 free(9CCCFF25C00)
2023/05/12 07:16:40.246 [debug] 97512#593595 free(9CCCFF31D00)
2023/05/12 07:16:40.246 [debug] 97512#593595 listen event count: 2
2023/05/12 07:16:40.246 [debug] 97512#593595 kevent(21) changes:0 timeout:-1
    handle = self._call_soon(callback, args, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/run_unit_0/Builds/Python-3.11/lib/python3.11/asyncio/base_events.py", line 781, in _call_soon
    handle = events.Handle(callback, args, self, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: <class 'asyncio.events.Handle'> returned a result with an exception set
2023/05/12 07:16:40.249 [debug] 45486#154438 [unit] recvmsg(10) failed: Resource temporarily unavailable (35)
2023/05/12 07:16:40.249 [debug] 45486#154438 [unit] port{45486,0} recvmsg -1
2023/05/12 07:16:40.249 [debug] 45486#154438 [unit] asgi_port_read(0x9cd7cc02108,0x9cd1b8dfd80): 2
`

**Comment by travisbell** [comment] 2023-05-12 15:36
Looks like maybe the same bug as reported [here](https://github.com/nginx/unit/issues/793)?

**Comment by ac000** [comment] 2023-05-12 17:21
Some quick questions.

1) Does this happen 100% of the time, i.e for every request?
2) What OS is this on? Mentions of kevent and kqueue in the log make me think FreeBSD...
3) Is this using ASGI?

This may be a big ask, but are you able to distil this down to a simple test application?

I can try reproducing this with a very basic application. I'm also always testing with IPv6 though normally just ```::1```

**Comment by SunFulong** [comment] 2023-05-12 18:12
> Does this happen 100% of the time, i.e for every request?
Yes, every IPv6 address request will fail, but IPv4 works.
> What OS is this on? Mentions of kevent and kqueue in the log make me think FreeBSD...
Gentoo Linux.
> Is this using ASGI?
Yes.

**Comment by ac000** [comment] 2023-05-12 20:05
Looks like I can reproduce this.

**Comment by ac000** [comment] 2023-05-13 17:08
Looks like ASGI never worked with IPv6... while I do use IPv6 by default, I have never got an ASGI app to actually run until now. It also seems our test framework is lacking some IPv6 coverage.

The problem is we are trying to split the port number from the IP address e.g [2001:db8::1]:8080 into '2001:db8::1' & '8080', however they are already separated. I think that would also be wrong as we don't handle the '[]'.

So we look for the ':', find it, loose the first 16bits of the address and try and use ':db8::1' as the port number which breaks the _PyLong_FromString()_ function. Of course this issue doesn't hit with IPv4.

The below patch seems to fix things

```diff
diff --git a/src/python/nxt_python_asgi.c b/src/python/nxt_python_asgi.c
index adf03e2b..9f6cde3b 100644
--- a/src/python/nxt_python_asgi.c
+++ b/src/python/nxt_python_asgi.c
@@ -828,7 +828,7 @@ nxt_py_asgi_create_address(nxt_unit_sptr_t *sptr, uint8_t len, uint16_t port)
 static PyObject *
 nxt_py_asgi_create_ip_address(nxt_unit_sptr_t *sptr, uint8_t len, uint16_t port)
 {
-    char      *p, *s;
+    char      *p;
     PyObject  *pair, *v;
 
     pair = PyTuple_New(2);
@@ -837,9 +837,8 @@ nxt_py_asgi_create_ip_address(nxt_unit_sptr_t *sptr, uint8_t len, uint16_t port)
     }
 
     p = nxt_unit_sptr_get(sptr);
-    s = memchr(p, ':', len);
 
-    v = PyString_FromStringAndSize(p, s == NULL ? len : s - p);
+    v = PyString_FromStringAndSize(p, len);
     if (nxt_slow_path(v == NULL)) {
         Py_DECREF(pair);
 
@@ -848,14 +847,7 @@ nxt_py_asgi_create_ip_address(nxt_unit_sptr_t *sptr, uint8_t len, uint16_t port)
 
     PyTuple_SET_ITEM(pair, 0, v);
 
-    if (s != NULL) {
-        p += len;
-        v = PyLong_FromString(s + 1, &p, 10);
-
-    } else {
-        v = PyLong_FromLong(port);
-    }
-
+    v = PyLong_FromLong(port);
     if (nxt_slow_path(v == NULL)) {
         Py_DECREF(pair);
 
```

**Comment by alejandro-colomar** [comment] 2023-05-17 07:44
> Looks like ASGI never worked with IPv6... while I do use IPv6 by default, I have never got an ASGI app to actually run until now. It also seems our test framework is lacking some IPv6 coverage.
> 
> The problem is we are trying to split the port number from the IP address e.g [2001:db8::1]:8080 into '2001:db8::1' & '8080', however they are already separated. I think that would also be wrong as we don't handle the '[]'.
> 
> So we look for the ':', find it, loose the first 16bits of the address and try and use ':db8::1' as the port number which breaks the _PyLong_FromString()_ function. Of course this issue doesn't hit with IPv4.
> 
> The below patch seems to fix things
> 
> ```diff
> diff --git a/src/python/nxt_python_asgi.c b/src/python/nxt_python_asgi.c
> index adf03e2b..9f6cde3b 100644
> --- a/src/python/nxt_python_asgi.c
> +++ b/src/python/nxt_python_asgi.c
> @@ -828,7 +828,7 @@ nxt_py_asgi_create_address(nxt_unit_sptr_t *sptr, uint8_t len, uint16_t port)
>  static PyObject *
>  nxt_py_asgi_create_ip_address(nxt_unit_sptr_t *sptr, uint8_t len, uint16_t port)
>  {
> -    char      *p, *s;
> +    char      *p;
>      PyObject  *pair, *v;
>  
>      pair = PyTuple_New(2);
> @@ -837,9 +837,8 @@ nxt_py_asgi_create_ip_address(nxt_unit_sptr_t *sptr, uint8_t len, uint16_t port)
>      }
>  
>      p = nxt_unit_sptr_get(sptr);
> -    s = memchr(p, ':', len);
>  
> -    v = PyString_FromStringAndSize(p, s == NULL ? len : s - p);
> +    v = PyString_FromStringAndSize(p, len);
>      if (nxt_slow_path(v == NULL)) {
>          Py_DECREF(pair);
>  
> @@ -848,14 +847,7 @@ nxt_py_asgi_create_ip_address(nxt_unit_sptr_t *sptr, uint8_t len, uint16_t port)
>  
>      PyTuple_SET_ITEM(pair, 0, v);
>  
> -    if (s != NULL) {
> -        p += len;
> -        v = PyLong_FromString(s + 1, &p, 10);
> -
> -    } else {
> -        v = PyLong_FromLong(port);
> -    }
> -
> +    v = PyLong_FromLong(port);
>      if (nxt_slow_path(v == NULL)) {
>          Py_DECREF(pair);
>  
> ```

Assuming the text above the patch is more or less what will go to the commit log:

```
Reviewed-by: Alejandro Colomar <alx@nginx.com>
```

**Comment by SunFulong** [comment] 2023-05-17 08:53
@alejandro-colomar This works!

**Comment by ac000** [comment] 2023-05-18 22:17
This fix has been merged.

**Closed by ac000** 2023-05-18 22:17 UTC
Labels: bug 🐞
