### ISSUE TITLE
Internal redirect from application

### ISSUE THREAD

**Issue by do11** [nginx/unit#503] opened 2020-11-24 05:05 UTC
Is it possible in Unit to do internal redirect (which will be handled by Unit and not by a browser) to other location inside of Unit caused by application. For example, application could prepare missing files and redirect to them leaving file serving work (which is hard) to the Unit.

**Comment by VBart** [comment] 2020-11-24 13:47
It's not possible yet. But it's in our plans to add such feature.

**Comment by lcrilly** [comment] 2023-03-27 08:32
Duplicate of https://github.com/nginx/unit/issues/764

**Closed by lcrilly** 2023-03-27 08:32 UTC
Labels: enhancement ⬆️
