### ISSUE TITLE
strange error when serving app from starlette

### ISSUE THREAD

**Issue by sandeep-gh** [nginx/unit#635] opened 2022-01-25 19:14 UTC
I get 503 error when running nginx+unit serving the example starlette app (https://unit.nginx.org/howto/starlette/). 
The complete log for unit is:
```
2022/01/26 00:37:51 [info] 33216#139127 discovery started
2022/01/26 00:37:51 [notice] 33216#139127 module: python 3.10.2 "/home/shared/Builds/unit-1.26.1/modules/python3.10.unit.so"
2022/01/26 00:37:51 [info] 36261#518939 controller started
2022/01/26 00:37:51 [notice] 36261#518939 process 33216 exited with code 0
2022/01/26 00:37:51 [info] 58715#394694 router started
2022/01/26 00:37:51 [info] 58715#394694 OpenSSL 1.1.1l  24 Aug 2021, 101010cf
2022/01/26 00:37:51 [info] 93430#495270 "myapp" prototype started
2022/01/26 00:37:51 [info] 32427#513572 "myapp" application started
2022/01/26 00:38:30 [alert] 32427#513572 [unit] #8: Python failed to create 'client' pair
2022/01/26 00:38:30 [alert] 32427#513572 [unit] Python failed to call 'loop.call_soon'
Traceback (most recent call last):
  File "/home/shared/Builds/Python-3.10.2/lib/python3.10/asyncio/base_events.py", line 745, in call_soon
    self._check_closed()
ValueError: invalid literal for int() with base 10: ''
```

I am using Python3.10.2. I have nginx pointing to unit via unix socket. The error is very strange I am not able to figure what could be wrong. 
Happy to provide any more information as needed.

**Comment by mar0x** [comment] 2022-01-25 20:58
Hello,

Most likely it caused by listening on unix socket. The code in ASGI module tries to parse remote address and extract host and port from the address - this need to be fixed.

For now, please try to reconfigure Unit to listen on TCP port.

**Comment by VBart** [comment] 2022-01-25 21:06
I guess you can workaround it by configuring `client_ip`: https://unit.nginx.org/configuration/#configuration-listeners-xff

**Comment by sandeep-gh** [comment] 2022-01-26 03:20
@VBart I am not sure I follow. It would be great if there is workaround for this. Could we add support of unix sockets?

**Comment by sandeep-gh** [comment] 2022-01-26 03:23
> 
@mar0x I have switched to sockets. I don't get the error anymore. However, I am still not able to serve the pages. I get "Not Found" message Seems to me that the app is crashing. Where can I see app's output. 

Below is the log from unit:
```
2022/01/26 08:45:00 [info] 80450#237461 "myapp" application started
2022/01/26 08:45:00 [notice] 72761#402719 app process (isolated 50225) exited with code 0
2022/01/26 08:45:00 [notice] 84238#260579 process 72761 exited with code 0
```

**Comment by mar0x** [comment] 2022-01-26 10:26
1. enable [access log](https://unit.nginx.org/configuration/#access-log) in Unit;
2. send the requests and check the access log;
3. if there is no requests in Unit access log, "Not Found" is generated by nginx, check nginx configuration; send requests directly to Unit;

Application stdout is redirected to /dev/null; stderr redirected to `unit.log`. To see app stdout, restart Unit with `--no-daemon`  command line option.

Please share your configuration file(s) and unit.log.

**Comment by sandeep-gh** [comment] 2022-01-26 14:57
I simplified the routing and the  starlette-howto app is working now. I have some issue with websockets but will debug that independently. 
Thank you, greatly,  for promptly fixing this. Can I hope to see unix socket support or are there reasons to not use sockets here? 
Again, much appreciate the help.

**Comment by VBart** [comment] 2022-01-26 15:42
> @VBart I am not sure I follow. It would be great if there is workaround for this. Could we add support of unix sockets?

The problem is caused by the fact that the client IP address in your case appears to be not IP, but unix socket. If you'd like to provide the real client IP address that is (I assume) connecting to your frontend server via TCP, then you need to configre `X-Forwarded-For` header field on your frontend: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

On the Unit side in order to support passing real client IP via `X-Forwarded-For`, you need to configure `client_ip` option.

**Comment by echolimazulu** [comment] 2022-03-25 21:17
I am closing this PR as it duplicates the issue: https://github.com/nginx/unit/issues/635.

> > @VBart I am not sure I follow. It would be great if there is workaround for this. Could we add support of unix sockets?
> 
> The problem is caused by the fact that the client IP address in your case appears to be not IP, but unix socket of nginx. If you'd like to provide the real client IP address that is (I assume) connecting to your nginx server via TCP, then you need to configre `X-Forwarded-For` header field on your nginx: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For
> 
> See here for nginx configuration: https://unit.nginx.org/howto/integration/#fronting-unit-with-nginx
> 
> On the Unit side in order to support passing real client IP via `X-Forwarded-For`, you need to configure the `client_ip` option.

@VBart, Good morning!

Unfortunately, the solution you suggested, with the implementation of the PR extension https://github.com/nginx/unit/pull/655 by @alejandro-colomar, only solves the `client ip` part of the problem using `X-Forwarded-For`.

I have created a repository with the ability to quickly reproduce this problem in just one command: https://github.com/echolimazulu/unit-asgi-503

@alejandro-colomar, Good morning! 

This is what you requested earlier in issue https://github.com/nginx/unit/issues/642

Please pay attention to the possibility of finding a solution to this problem based on the data I provided. 

Thank you very much for your attention to this issue!

**Comment by alejandro-colomar** [comment] 2022-03-28 14:05
Hi!

Thank you very much for the reproducer repo.  Will play with it to understand the problem!

Cheers,
Alex

**Comment by echolimazulu** [comment] 2022-03-29 13:30
> I traced the 503 error source to `src/nxt_router.c:4508`:
> 
> https://github.com/alejandro-colomar/unit/blob/91ba4f138cdb7581cfbd9a426b8a180e2173e6b0/src/nxt_router.c#L4508

@alejandro-colomar, Hello Alejandro!

**Thank you for the work you have done!** 

I'm really glad that I helped you reproduce this problem. 
I am sure that this information will help to understand the causes of the problem much more quickly.

**Comment by tippexs** [comment] 2022-03-30 16:01
Hi @alejandro-colomar please have a look here. as discussed. https://github.com/nginx/unit/blob/aeed86c6829c62359e79f239b849766efb8857a7/src/python/nxt_python_asgi.c#L1084

**Comment by alejandro-colomar** [comment] 2022-03-30 18:11
I changed your repository a bit to serve a static website instead of a python/falcon app, and it works.  So we need to fix the code for python ASGI, as @mar0x said.

**Comment by alejandro-colomar** [comment] 2022-03-30 18:17
> Hi @alejandro-colomar please have a look here. as discussed.
> 
> https://github.com/nginx/unit/blob/aeed86c6829c62359e79f239b849766efb8857a7/src/python/nxt_python_asgi.c#L1084

I think this is failing even before the port thing.  I remember seeing this error in the log too:

https://github.com/nginx/unit/blob/aeed86c6829c62359e79f239b849766efb8857a7/src/python/nxt_python_asgi.c#L666

Line 666, BTW xD

We'll check later.

**Comment by alejandro-colomar** [comment] 2022-03-30 19:08
https://github.com/nginx/unit/blob/aeed86c6829c62359e79f239b849766efb8857a7/src/python/nxt_python_asgi.c#L748

```
ALX: DBG: nxt_py_asgi_create_address(): p=10.10.10.10
ALX: DBG: nxt_py_asgi_create_address(): p=unix:///var/run/falcon.sock
```

That `:` is the one that's causing the error (it's being interpreted as the address:port separator, and then the string after it can't be interpreted as a port.

**Comment by alejandro-colomar** [comment] 2022-04-01 10:22
Okay, we have a fix.  There's something we don't know, and that's if I need to `Py_INCREF(Py_None)` or not.  I'll open a PR soon, so you can check it, but the fix is already in my test branch, so you can have a look at it: <https://github.com/alejandro-colomar/unit/tree/sock-test>.

**Comment by echolimazulu** [comment] 2022-04-01 11:24
@alejandro-colomar, Good afternoon!

This works incredibly well for me! 

I've been trying to do something about it all morning, but unfortunately my knowledge was not enough to deal with it. Your decision really impressed me! 

Thank you so much!

**Closed** 2022-06-19 10:29 UTC
Labels: bug 🐞
