### ISSUE TITLE
Disable access log for specific routes

### ISSUE THREAD

**Issue by aalsmile** [nginx/unit#797] opened 2022-12-06 19:50 UTC
Could you tell me how can I disable access logging for specific routes like health check or if that option doesn't currently exist, could you add the issue to backlog? Regards for developers.

**Comment by tippexs** [comment] 2022-12-08 10:16
Hi @aalsmile at the moment this is not possible but we are talking about different configuration options for our access and error logs. I would like to flag this as enhancement and keep the issue open.

**Comment by lcrilly** [comment] 2023-10-20 07:46
Closing as duplicate of https://github.com/nginx/unit/issues/594

**Closed by lcrilly** 2023-10-20 07:46 UTC
Labels: enhancement ⬆️
