### ISSUE TITLE
php ini options  are reset to defaults after the first request ?

### ISSUE THREAD

**Issue by shan307** [nginx/unit#149] opened 2018-07-12 07:43 UTC
/usr/local/bin/curl --unix-socket /var/run/control.unit.sock http://localhost
{
        "listeners": {
                "*:8003": {
                        "application": "php-unit3"
                }
        },

        "applications": {
                "php-unit3": {
                        "type": "php",
                        "user": "apps",
                        "processes": 4,
                        "root": "/home/apps/heshan/nginx_unit/php/",
                        "index": "index.php",
                        "options": {
                                "file": "/apps/conf/php5/php.ini",
                                "admin": {
                                        "memory_limit": "100M",
                                        "display_errors": "1",
                                        "post_max_size": "100M"
                                }
                        }
                }
        }
}

**first request result:**
curl http://localhost:8003/get_ini.php
display_errors = 1
memory_limit = 100M
post_max_size = 100M

**second request result:**
curl http://localhost:8003/get_ini.php                                       
display_errors = 
memory_limit = 821M
post_max_size = 8M

**php.ini default parameters:**
cat /apps/conf/php5/php.ini | grep -E "display_errors|memory_limit|post_max_size"
memory_limit = 821M
display_errors = Off
post_max_size = 8M

Another question:
Can we increase the parameter via rest api?

**Comment by VBart** [comment] 2018-07-12 09:36
Duplicate of #145.

**Closed by VBart** 2018-07-12 09:36 UTC
Labels: bug, duplicate
